// export const serverRows = [
//   {
//     no:1,id: 1,
//     no: "1",
//     fullName: "Muheto Hodal",
//     email: "mhthodol@gmail.com",
//     serverNo: "24033",
//     openedDate: "20-02-2022",
//     closedDate: "03-11-2022",
//   },
//   {
//     no:1,id: 2,
//     no: "2",
//     fullName: "Jean Claude",
//     email: "mhthodol@gmail.com",
//     serverNo: "44033",
//     openedDate: "03-03-2022",
//     closedDate: "03-12-2022",
//   },
//   {
//     no:1,id: 3,
//     no: "3",
//     fullName: "Muneza Keza",
//     email: "mhthodol@gmail.com",
//     serverNo: "56033",
//     openedDate: "11-02-2022",
//     closedDate: "03-02-2022",
//   },
// ];

export const serverRows = [
  {
    no: 1,
    id: 1,
    userName: "John Snow",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlhNq4jCXT754rhAhZ3P0fvmlQXSbCcc1v-rqcGl0e&s",
    email: "jon@gmail.com",
    status: "Off Line",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 2,
    id: 2,
    userName: "Mathiew JMV",
    avatar: "https://i.ytimg.com/vi/dvXNk8f-qek/maxresdefault.jpg",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 3,
    id: 3,
    userName: "Umwiza joella",
    avatar:
      "https://inyarwanda.com/app/webroot/img/202202/images/medium_thumbs/photo-6-6157661644957012.jpg",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 4,
    id: 4,
    userName: "Mugeni Keza",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRff-JZvSvUIuoIILVU2Ue1vJKgMQ4OJLGYaA&usqp=CAU",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 5,
    id: 5,
    userName: "Peter joshua",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRff-JZvSvUIuoIILVU2Ue1vJKgMQ4OJLGYaA&usqp=CAU",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 6,
    id: 6,
    userName: "Kamonyo Vincent",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRff-JZvSvUIuoIILVU2Ue1vJKgMQ4OJLGYaA&usqp=CAU",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 7,
    id: 7,
    userName: "Mugabo ningwe",
    avatar: "https://ae03.alicdn.com/kf/H80dd08e089614ce4a857f367014970d2k.jpg",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 8,
    id: 8,
    userName: "Tuyizere Donatie",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRff-JZvSvUIuoIILVU2Ue1vJKgMQ4OJLGYaA&usqp=CAU",
    email: "jon@gmail.com",
    status: "active",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 9,
    id: 9,
    userName: "Sylvain Niyonkuru",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRff-JZvSvUIuoIILVU2Ue1vJKgMQ4OJLGYaA&usqp=CAU",
    email: "jon@gmail.com",
    status: "offline",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
  {
    no: 10,
    id: 10,
    userName: "Muheto Hodal",
    avatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRff-JZvSvUIuoIILVU2Ue1vJKgMQ4OJLGYaA&usqp=CAU",
    email: "jon@gmail.com",
    status: "offline",
    serverNo: "24033",
    openedDate: "20-02-2022",
    closedDate: "03-11-2022",
    action: ["update"],
  },
];
